name: Deploy log4j2 plugin
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: nationalarchives/dr2-github-actions/.github/workflows/sbt_release.yml@d363fe45d8eea14d3a5271f20fc26dba6b14304c
    with:
      library-name: "sbt-assembly log4j2 plugin"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
