name: DR2 Run Lambda Tests
on:
  push:
    branches-ignore:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: nationalarchives/dr2-github-actions/.github/workflows/dr2_test.yml@d363fe45d8eea14d3a5271f20fc26dba6b14304c
    with:
      repo-name: sbt-assembly-log4j2
      test-command: sbt scalafmtCheckAll test scripted
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
